### PR TITLE
Add support for more languages

### PR DESCRIPTION
**Pull request by ashpect**
Fixing #33 's bugs one by one.

- [x] node
- [x] py
- [x] ruby
- [x] java
- [x] cobol
- [x] ts
- [] go
- [] rust

### CODE REVIEW

**Comment by ashpect** [comment]
Will need to refactor test workflow to avoid getting space limited.

**Comment by viferga** [comment]
The CI is failing and there are conflicts, should I merge this...?

**Comment by ashpect** [comment]
> Fixing #33 's bugs one by one.
> 
> * [x]  node
> * [x]  py
> * [x]  ruby
> * [x]  java
> * [x]  cobol
> * [x]  ts
> * [] go
> * [] rust

Not now, when I fix the remaining 2 languages, then we can merge. I'll edit it to a WIP pr

**Comment by viferga** [comment]
Amazing, great job @ashpect .

**Comment by ashpect** [comment]
Mergable.
Opened issues for remaining languages, ie , go and rust

> > Fixing #33 's bugs one by one.
> > 
> > * [x]   node
> > * [x]   py
> > * [x]   ruby
> > * [x]   java
> > * [x]   cobol
> > * [x]   ts
> > * [] go
> > * [] rust
> 
> Not now, when I fix the remaining 2 languages, then we can merge. I'll edit it to a WIP pr

**Comment by viferga** [comment]
@ashpect I see the startup test is still failing, are we able to merge and delay this feature, or you are going to implement it?

**Comment by ashpect** [comment]
```
@Error : DynLink error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /lib/x86_64-linux-gnu/libicui18n.so.72) [Sun Oct 6 02:50:46] #7 @Error : Failed to load library from plugin descriptor [Sun Oct 6 02:50:46] #7 @Error : Plugin loader from manager 'loader' failed to load plugin: node [Sun Oct 6 02:50:46] #7 @Error : Failed to create loader: node [Sun Oct 6 02:50:46] #7 @Error : Tried to load 1 file(s) from non existent loader (node): /usr/local/lib/plugins/cli/internal/cli_cmd_plugin/cli_cmd_plugin.js [Sun Oct 6 02:50:46] #7 @Error : Loader load from configuration invalid load from file [Sun Oct 6 02:50:46] #7 @Error : Failed to load plugin: /usr/local/lib/plugins/cli/internal/cli_cmd_plugin/metacall.json Failed to load CLI plugins from folder '/usr/local/lib/plugins/cli/internal' with result: 4'
```
Yes, there is some error. I'll check once by triggering them seperately to see which language failed

**Comment by ashpect** [comment]
@viferga To prevent confusion, I'm closing this Pr and closed the previous one. I've opened an issue mentioning the status of the languages supported [i,e 6/10] and also a small PR uncommenting java and wasm. I think it's better to start fresh with the remaining 4 to avoid confusion and avoid getting stale.

**Comment by ashpect** [comment]
@viferga To prevent confusion, I'm closing this Pr and closed the previous one. I've opened an issue mentioning the status of the languages supported [i,e 6/10] and also a small PR uncommenting java and wasm. I think it's better to start fresh with the remaining 4 to avoid confusion and avoid getting stale.

**Pull request closed without merging**
