### PR TITLE
[DO NOT MERGE] Trigger tests

### PR DESCRIPTION
**Pull request by ashpect**
NOT FOR MERGING PURPOSES, triggering tests to document why some language fails and fix their bugs one by one.

### CODE REVIEW

**Comment by ashpect** [comment]
We'll be documenting why other languages test fail and fixing them on the go.

Tests failed for typescript
- install npm in base

**Comment by ashpect** [comment]
- [] c 
```
metacall_builder_rootless  |  > bash /usr/local/metacall/tools/metacall-runtime.sh base backtrace ports clean c:
metacall_builder_rootless  | 7.495 Saving to: 'STDOUT'
metacall_builder_rootless  | 7.496 
metacall_builder_rootless  | 7.496      0K ...                                                   100% 51.7M=0s
metacall_builder_rootless  | 7.496 
metacall_builder_rootless  | 7.496 2024-08-26 23:04:25 (51.7 MB/s) - written to stdout [3145/3145]
metacall_builder_rootless  | 7.496 
metacall_builder_rootless  | 7.749 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
metacall_builder_rootless  | 7.983 gpg: error running '/usr/bin/gpg-agent': probably not installed
metacall_builder_rootless  | 7.983 gpg: failed to start agent '/usr/bin/gpg-agent': Configuration error
metacall_builder_rootless  | 7.983 gpg: can't connect to the agent: Configuration error
metacall_builder_rootless  | ------
metacall_builder_rootless  | error: failed to solve: process "bash /usr/local/metacall/tools/metacall-runtime.sh base backtrace ports clean c" did not complete successfully: exit code: 2
Aborting on container exit...
```

**Comment by ashpect** [comment]
- [] go

**Comment by viferga** [comment]
Should I merge this, there's conflicts...

**Comment by ashpect** [comment]
> NOT FOR MERGING PURPOSES, triggering tests to document why some language fails and fix their bugs one by one.

This is just for testing purposes, as written in description. Tests weren't getting triggered without opening a pr. 
As you can see above, in gh actions tests for each lang were triggered.
c, go and rust are left . Cobol, ts, etc got completed.

**Comment by viferga** [comment]
Ok, cool sorry for that, I am removing the draft thing otherwise the CI won't work. Ping me if you have any problem with the CI.

**Comment by ashpect** [comment]
Closing PR, mentioned in issue #36 for reference.

**Pull request closed without merging**
